name: Build project

on: [push]

jobs:
  buildForAllSupportedPlatforms:
    if: github.ref == 'refs/heads/master'
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3.2.6
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      #- uses: game-ci/unity-test-runner@v2.1.1
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #  with:
      #    githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: game-ci/unity-builder@v2.2.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: codfish/semantic-release-action@v2
        with:
          dry_run: true
          branches: |
            [
              'master'
            ]
          repository_url: https://github.com/Haleralex/CICDTest.git
          tag_format: 'v${version}'
          
          extends: '@semantic-release/apm-config'
          additional_packages: |
            ['@semantic-release/apm@4.0.0', '@semantic-release/git']
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github', '@semantic-release/apm', '@semantic-release/git']
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      - uses: appleboy/telegram-action@master
        name: send default message
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: build/${{ matrix.targetPlatform }}/Android.apk
